language: python
script:
- python -m pytest -v
notifications:
  slack:
    secure: Ip5dX9SUnEm+tkRVGDSPiTM3mb2znt4qclcWBlHcwObngnCzYo7X4hMir08nII49lg3NEd7Y8euYM+gN6yeELSB1FwJZiXW2mrOZOmnZe3PBSW3yrf28PIquPoRU/d41DalYYz2hk5yJARw+TWJ7mhGJUh0zUfAWYN62d7NuNeDa1GtgW6M6tfSj21PhgGsXRHEqkLo1aCYbvYW1Ir8oXDfBykRjcMggnP+ffV3pVdq9wX7DkVNkOKXQPqPKXIe8TkXuk/mluHh3EW3c2kaGGgpuxg7UPkyU+vVfkzlSMU3N95sf7UmpS8iZae557FiwYuje+jIWkeNYwTFBOmpBGWAwLvGE9+NDttMh6V2Z0U26wAC6XWmRi3t5g6Sd3KIelgeqyAmosovWZL5eJPe2l8aOSuPoAYHIb+YKFEfTgUhuwhaavM+6/67MTo8IXrClqoMY5Xbnz2WywKpwD5AcF7L6couow9fFX9cIRqNb1AC2fzSTX7riPGhEAoVsiZWc1NcNHuzV6VQaj41EYgTe8CQGDgfu7atAG+iprxKbQQgkuObOiguprNaMT32KhmhNq9bRNP8fguMN8n1jq1uCpI1cBbWPSuhVyl6tLfWXqr4MdMPOr4OiNkO7wULOu0OQoszp0InVMRDi0GfzizAWsc7NmlZ3w0VqlQqVfzIHy3Y=
